PortalGuitarFlash.Web/Controllers/ChangeLogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PortalGuitarFlash.DDD.Entities;
using PortalGuitarFlash.Infra.Data.Context;
using PortalGuitarFlash.DDD.Interfaces.Repositories;
using PortalGuitarFlash.Infra.Data.Repositories;
using PortalGuitarFlash.Web.ViewModels;
using AutoMapper;

namespace PortalGuitarFlash.Web.Controllers
{
    [Authorize]
    public class ChangeLogController : Controller
    {

        protected static readonly IChangeLogRepository repo = new ChangeLogRepository();

        [AllowAnonymous]
        public ActionResult Index()
        {
            IEnumerable<ChangeLog> progresses = repo.GetAll().OrderByDescending(w => w.StartDate);
            return View(Mapper.Map<IEnumerable<ChangeLogViewModel>>(progresses));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Type,Description,Status,StartDate")] ChangeLogViewModel changeLog)
        {
            if (ModelState.IsValid)
            {
                ChangeLog c = Mapper.Map<ChangeLog>(changeLog);
                repo.Add(c);
                return RedirectToAction("Index");
            }

            return View(changeLog);
        }

        public ActionResult Edit(int id)
        {
            ChangeLog changeLog = repo.GetById(id);
            if (changeLog == null)
                return HttpNotFound();
            ChangeLogViewModel vm = Mapper.Map<ChangeLogViewModel>(changeLog);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ChangeLogId,Type,Description,Status,StartDate")] ChangeLogViewModel changeLog)
        {
            if (ModelState.IsValid)
            {
                ChangeLog current = repo.GetById(changeLog.ID);
                ChangeLog c = Mapper.Map<ChangeLogViewModel, ChangeLog>(changeLog, current);
                repo.Update(c);
                return RedirectToAction("Index");
            }
            return View(changeLog);
        }

        public ActionResult Delete(int id)
        {
            ChangeLog changeLog = repo.GetById(id);
            if (changeLog == null)
                return HttpNotFound();
            ChangeLogViewModel vm = Mapper.Map<ChangeLogViewModel>(changeLog);
            return View(vm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ChangeLog changeLog = repo.GetById(id);
            repo.Remove(changeLog);
            return RedirectToAction("Index");
        }

    }
}

PortalGuitarFlash.Web/Controllers/HomeController.cs
using AutoMapper;
using PortalGuitarFlash.Web.AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalGuitarFlash.Web.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

    }
}

PortalGuitarFlash.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
    <!-- Header -->
@section Featured {
<div class="intro-header">
    <div class="container">

    <div class="top-padding">
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>PORTAL EM CONSTRUÇÃO! </strong> Veja @Html.ActionLink("aqui", "Index", "ChangeLog") a lista do que está em progresso!
        </div>
        @*<div class="row">
                <div class="panel panel-default panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">PORTAL EM CONSTRUÇÃO</h3>
                    </div>
                    <div class="panel-body">

                    </div>
                </div>
            </div>*@
    </div>




        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Portal do Guitar Flash</h1>
                    <h3>Seja bem-vindo(a) ao novo portal do guitar flash, onde você poderá encontrar diversas músicas para jogar.</h3>
                    <hr class="intro-divider">
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <a target="_blank" href="http://www.guitarflash.com/" class="btn btn-default btn-lg"><i class="fa fa-gamepad fa-fw"></i> <span class="network-name">Guitar Flash</span></a>
                        </li>
                        <li>
                            <a target="_blank" href="https://apps.facebook.com/guitarflash" class="btn btn-default btn-lg"><i class="fa fa-facebook-square fa-fw"></i> <span class="network-name">Facebook</span></a>
                        </li>
                        <li>
                            <a target="_blank" href="https://twitter.com/guitarflashx" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.intro-header -->
<!-- Page Content -->
 }

<div class="content-section-b">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">O que você encontra aqui?</h2>
                <p class="lead">Diversas músicas publicadas pelos próprios jogadores, disponíveis para download. Uma vez feito o download, você pode jogar no <a target="_blank" href="http://www.guitarflash.me/custom/">Guitar Flash Custom</a></p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <img class="img-responsive" src="~/img/guitar-flash.png" alt="">
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->

<div class="content-section-a">

    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Publique suas próprias <b>charts</b> para outros jogadores...</h2>
                <p class="lead">Crie suas próprias charts para suas músicas preferidas e publique para que outros possam jogar e avaliar seu trabalho. Para desenvolver, a ferramenta mais indicada pelo próprio criador do jogo é o <a target="_blank" href="https://code.google.com/p/freetar/">Freetar Editor</a>!</p>
            </div>
            <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                <img class="img-responsive" src="~/img/freetar.png" alt="">
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-b -->

<div class="content-section-b">

    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Seja reconhecido pela comunidade!</h2>
                <p class="lead">Se você fizer um bom trabalho, poderá ter seu nome destacado entre os melhores <b>charters</b> do jogo!</p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <img class="img-responsive" src="~/img/ranking.jpg" alt="">
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->
@*	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Guitar Flash nas Redes Sociais</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>*@
<!-- /.banner -->