PortalGuitarFlash.Web/Controllers/AuthorController.cs
using AutoMapper;
using PortalGuitarFlash.DDD.Entities;
using PortalGuitarFlash.DDD.Interfaces.Repositories;
using PortalGuitarFlash.Infra.Data.Repositories;
using PortalGuitarFlash.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalGuitarFlash.Web.Controllers
{
    public class AuthorController : Controller
    {

        protected static readonly IAuthorRepository repo = new AuthorRepository();

        public ActionResult Index()
        {
            IEnumerable<Author> authors = repo.GetAll().OrderByDescending(a => a.Name.Length).Take(10);
            return View(Mapper.Map<IEnumerable<AuthorViewModel>>(authors));
        }

        public ActionResult Edit(int id)
        {
            Author author = repo.GetById(id);
            if (author == null)
                return HttpNotFound();
            AuthorViewModel a = Mapper.Map<AuthorViewModel>(author);
            return View(a);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AuthorId,Name")] AuthorViewModel author)
        {
            if (ModelState.IsValid)
            {
                Author current = repo.GetById(author.ID);
                Author a = Mapper.Map<AuthorViewModel, Author>(author, current);
                repo.Update(a, true);
                return RedirectToAction("Index");
            }
            return View(author);
        }

    }
}

PortalGuitarFlash.Web/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalGuitarFlash.Web.Controllers
{
    public class NewsController : Controller
    {
        // GET: NewSubmission
        public ActionResult Index()
        {
            return View();
        }

    }
}

PortalGuitarFlash.Web/Controllers/SongController.cs
using AutoMapper;
using PortalGuitarFlash.DDD.Entities;
using PortalGuitarFlash.DDD.Helpers;
using PortalGuitarFlash.DDD.Interfaces.Repositories;
using PortalGuitarFlash.Infra.CrossCutting.EntitySearchBuilder.Orderers;
using PortalGuitarFlash.Infra.Data.Repositories;
using PortalGuitarFlash.Web.Helpers.Attributes;
using PortalGuitarFlash.Web.ViewModels;
using PortalGuitarFlash.Web.ViewModels.Song;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PortalGuitarFlash.Web.Controllers
{
    [AuthorizeMessage]
    public class SongController : Controller
    {

        public static readonly IExternalSongRepository repo = new ExternalSongRepository();

        [AllowAnonymous]
        public ActionResult Index(CollectionPageViewModel<ExternalSongViewModel> collectionPage = null)
        {

            PortalGuitarFlash.DDD.Entities.User user = Helpers.Helpers.GetLoggedUser();
            ViewBag.LoggedUserId = (user == null) ? 0 : user.ID;

            int page = collectionPage == null ? 1 : collectionPage.Pagina;
            int itemsPerPage = collectionPage == null ? 10 : collectionPage.Quantidade;
            string text = collectionPage == null ? "" : collectionPage.Texto;
            var builder = new SongListOrderer() { SearchText = text, SortingOrder = DDD.Enum.SortingType.Ascending };
            var paged = repo.GetAllPaged(page, itemsPerPage, builder);
            var songs = Mapper.Map<CollectionPageViewModel<ExternalSongViewModel>>(paged);
            return View(songs);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [AuthorizeMessage(Message="Para baixar uma música, é necessário estar logado!", Override=true)]
        public ActionResult Download(int id)
        {
            ExternalSong song = repo.GetById(id);
            if (song == null)
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            return Redirect(song.DownloadUrl);
        }

        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PortalGuitarFlash.Web/Controllers/UserController.cs
using AutoMapper;
using PortalGuitarFlash.DDD.Entities;
using PortalGuitarFlash.DDD.Interfaces.Repositories;
using PortalGuitarFlash.Infra.Data.Repositories;
using PortalGuitarFlash.Web.ViewModels;
using PortalGuitarFlash.Web.ViewModels.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalGuitarFlash.Web.Controllers
{
    public class UserController : Controller
    {

        public static readonly IUserRepository repo = new UserRepository();

        public ActionResult Index()
        {
            if (TempData["ErrorMessage"] != null)
                ViewBag.ErrorMessage = TempData["ErrorMessage"].ToString();
            IEnumerable<User> users = repo.GetAll().OrderByDescending(a => a.GetCharterPoints()).ThenBy(a => a.RegisterDate).Take(50);
            return View(Mapper.Map<IEnumerable<UserViewModel>>(users));
        }

        [HttpGet]
        [Route("profile/edit", Name = "Profile.Edit")]
        public ActionResult Edit()
        {
            User user = Helpers.Helpers.GetLoggedUser();
            if (user == null)
            {
                TempData["ErrorMessage"] = "Necessário estar logado para editar o perfil!";
                return RedirectToAction("Index");
            }
            ProfileViewModel model = Mapper.Map<ProfileViewModel>(user);
            return View(model);
        }

        [HttpPost]
        [Route("profile/edit", Name = "Profile.Save")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProfileViewModel profile)
        {
            if (ModelState.IsValid)
            {
                User current = repo.GetById(profile.ID);
                User user = Mapper.Map<ProfileViewModel, User>(profile, current);
                repo.Update(user);
                return RedirectToAction("ShowProfile");
            }
            return View(profile);
        }

        [Route("profile/{id:int?}", Name="Profile")]
        public ActionResult ShowProfile(int id = 0)
        {
            User user = id == 0 ? Helpers.Helpers.GetLoggedUser() : repo.GetById(id);
            if (user == null)
            {
                if (id != 0)
                    TempData["ErrorMessage"] = String.Format("Usuário de ID {0} não localizado!", id);
                return RedirectToAction("Index");
            }
            ProfileViewModel model = Mapper.Map<ProfileViewModel>(user);
            //model.ProfileImageUrl = Url.Action("UserProfileImage", "Image", new { userId = user.ID });
            return View("profile", model);
        }

    }
}

PortalGuitarFlash.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Portal do Guitar Flash - @ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @RenderSection("Content", required: false)

    @Scripts.Render("~/bundles/jquery")

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

</head>
<body>
    <div class="body-content">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top topnav" role="navigation">
            <div class="container topnav">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand topnav" href="#">Portal Guitar Flash</a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Novidades", "Index", "News")</li>
                        <li>@Html.ActionLink("Músicas", "Index", "Song")</li>
                        <li>@Html.ActionLink("Usuários", "Index", "User")</li>
                        <li>@Html.ActionLink("Bandas", "Index", "Author")</li>
                        @*<li>@Html.ActionLink("Conversor", "Index", "Converter")</li>*@
                        <li>@Html.ActionLink("Histórico de Mudanças", "Index", "ChangeLog")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                <div class="container">
                    <div class="row">
                        @if (ViewBag.ErrorMessage != null)
                        {
                            <div class="panel panel-danger">
                                <div class="panel-heading">
                                    @ViewBag.ErrorMessage
                                </div>
                            </div>
                        }

                        @RenderBody()
                    </div>
                </div>
            </section>
        </div>
    </div>

    <!-- Footer -->

    @*<nav class="navbar navbar-default">
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <p class="copyright text-muted small">Portal desenvolvido e mantido por <a href="https://www.facebook.com/alissonreinaldosilva">Alisson Reinaldo Silva</a>. Por favor, entre em contato caso detecte qualquer erro!</p>
                </div>
            </div>
        </footer>
    </nav>*@

    @RenderSection("Scripts", required: false)

</body>
</html>