PortalGuitarFlash.Web/ViewModels/User/ProfileViewModel.cs
using PortalGuitarFlash.Web.ViewModels.Song;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PortalGuitarFlash.Web.ViewModels.User
{
    public class ProfileViewModel
    {

        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Por favor, preencha seu nome!")]
        [MaxLength(100, ErrorMessage = "Seu nome deve conter no máximo {0} caracteres!")]
        [Display(Name="Nome")]
        public string Name { get; set; }
        [MaxLength(4000, ErrorMessage = "A descrição deve conter no máximo {0} caracteres!")]
        [Display(Name = "Descrição")]
        public string Description { get; set; }
        [MaxLength(100, ErrorMessage = "O título deve conter no máximo {0} caracteres!")]
        [Display(Name = "Título do Perfil")]
        public string DescriptionTitle { get; set; }
        [MaxLength(100, ErrorMessage = "O local deve conter no máximo {0} caracteres!")]
        [Display(Name = "Local")]
        public string Local { get; set; }
        public string Age { get; set; }
        [DataType(DataType.Date, ErrorMessage = "O valor digitado não é uma data válida!")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Data de Nascimento")]
        public DateTime? Birthday { get; set; }
        [MaxLength(100, ErrorMessage = "Seu skype deve conter no máximo {0} caracteres!")]
        public string Skype { get; set; }
        [MaxLength(100, ErrorMessage = "Seu Twitter deve conter no máximo {0} caracteres!")]
        [Display(Name = "Twitter")]
        [Url(ErrorMessage = "O link do seu Twitter não é uma URL válida!")]
        public string TwitterUrl { get; set; }
        [MaxLength(100, ErrorMessage = "Seu facebook deve conter no máximo {0} caracteres!")]
        [Display(Name = "Facebook")]
        [Url(ErrorMessage = "O link do seu Facebook não é uma URL válida!")]
        public string FacebookUrl { get; set; }
        [MaxLength(100, ErrorMessage = "Seu Google+ deve conter no máximo {0} caracteres!")]
        [Display(Name = "Google+")]
        [Url(ErrorMessage = "O link do seu Google+ não é uma URL válida!")]
        public string GooglePlusUrl { get; set; }
        public IEnumerable<ExternalSongViewModel> ExternalSongs { get; set; }


    }
}

PortalGuitarFlash.Web/ViewModels/User/UserViewModel.cs
using PortalGuitarFlash.Web.ViewModels.Song;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PortalGuitarFlash.Web.ViewModels
{
    public class UserViewModel
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Por favor, digite um nome!")]
        [MaxLength(255, ErrorMessage = "O nome deve ter até {0} caracteres!")]
        [DisplayName("Nome")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Por favor, digite um email!")]
        [MaxLength(255, ErrorMessage = "O email deve ter até {0} caracteres!")]
        public string Email { get; set; }
        [DisplayName("CP")]
        public int CharterPoints { get; set; }
        //[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm}", ApplyFormatInEditMode = true)]
        public DateTime RegisterDate { get; set; }
        //[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm}", ApplyFormatInEditMode = true)]
        public DateTime UpdateDate { get; set; }
        public IEnumerable<ExternalSongViewModel> ExternalSongs { get; set; }
    }
}

PortalGuitarFlash.Web/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PortalGuitarFlash.DDD.Entities;

namespace PortalGuitarFlash.Web.Controllers
{
    [RoutePrefix("image")]
    public class ImageController : Controller
    {
        [Route("user/{userId:int}/profile")]
        public ActionResult UserProfileImage(int userId)
        {
            User user = UserController.repo.GetById(userId);
            UserProfileImage img = user.Images.Where(i => i.Type == DDD.Enum.ImageType.Profile).FirstOrDefault();
            if (img == null)
                return File(Server.MapPath("~/img/unknown-person.gif"), "image/jpg");
            return File(img.Image, "image/jpg");
        }

    }
}

PortalGuitarFlash.Web/Controllers/UserController.cs
using AutoMapper;
using PortalGuitarFlash.DDD.Entities;
using PortalGuitarFlash.DDD.Interfaces.Repositories;
using PortalGuitarFlash.Infra.Data.Repositories;
using PortalGuitarFlash.Web.ViewModels;
using PortalGuitarFlash.Web.ViewModels.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalGuitarFlash.Web.Controllers
{
    public class UserController : Controller
    {

        public static readonly IUserRepository repo = new UserRepository();

        public ActionResult Index()
        {
            if (TempData["ErrorMessage"] != null)
                ViewBag.ErrorMessage = TempData["ErrorMessage"].ToString();
            IEnumerable<User> users = repo.GetAll().OrderByDescending(a => a.GetCharterPoints()).ThenBy(a => a.RegisterDate).Take(50);
            return View(Mapper.Map<IEnumerable<UserViewModel>>(users));
        }

        [HttpGet]
        [Route("profile/edit", Name = "Profile.Edit")]
        public ActionResult Edit()
        {
            User user = Helpers.Helpers.GetLoggedUser();
            if (user == null)
            {
                TempData["ErrorMessage"] = "Necessário estar logado para editar o perfil!";
                return RedirectToAction("Index");
            }
            ProfileViewModel model = Mapper.Map<ProfileViewModel>(user);
            return View(model);
        }

        [HttpPost]
        [Route("profile/edit", Name = "Profile.Save")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProfileViewModel profile)
        {
            if (ModelState.IsValid)
            {
                User current = repo.GetById(profile.ID);
                User user = Mapper.Map<ProfileViewModel, User>(profile, current);
                repo.Update(user);
                return RedirectToAction("ShowProfile");
            }
            return View(profile);
        }

        [Route("profile/{id:int?}", Name="Profile")]
        public ActionResult ShowProfile(int id = 0)
        {
            User user = id == 0 ? Helpers.Helpers.GetLoggedUser() : repo.GetById(id);
            if (user == null)
            {
                if (id != 0)
                    TempData["ErrorMessage"] = String.Format("Usuário de ID {0} não localizado!", id);
                return RedirectToAction("Index");
            }
            ProfileViewModel model = Mapper.Map<ProfileViewModel>(user);
            //model.ProfileImageUrl = Url.Action("UserProfileImage", "Image", new { userId = user.ID });
            return View("profile", model);
        }

    }
}

PortalGuitarFlash.Web/Views/User/Edit.cshtml
@model PortalGuitarFlash.Web.ViewModels.User.ProfileViewModel

@{
    ViewBag.Title = "Editar Perfil";
}

@using (Html.BeginForm("Edit", "User", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="container" id="main">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                <div id="sidebar">
                    <div class="user">
                        <div class="text-center">
                            <img src="@Url.Action("UserProfileImage", "Image", new { userId = Model.ID })" class="img-circle img-profile">
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="hr-center"></div>
                    </div>
                    <div class="link-me">

                        <div class="form-group">
                            @Html.LabelFor(model => model.Local)
                            @Html.EditorFor(model => model.Local, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Local, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Birthday)
                            @Html.EditorFor(model => model.Birthday,  new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon"><i class="fa fa-skype"></i></div>
                                @Html.EditorFor(model => model.Skype, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            @Html.ValidationMessageFor(model => model.Skype, "", new { @class = "text-danger" })
                        </div>
                        <div class="hr-center"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
                <div id="content">
                    <!-- start:navbar -->
                    <nav class="navbar navbar-default navbar-static-top" role="navigation">
                        <div class="navbar-header page-scroll">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse navbar-ex1-collapse">
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-check"></i> Salvar</button>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </nav>
                    <!-- end:navbar -->
                    <!-- start:main content -->
                    <div class="main-content">
                        <ul class="timeline">
                            <!-- start:profile -->
                            <li id="id-profile">
                                <div class="timeline-badge default"><i class="fa fa-user"></i></div>
                                <h1 class="timeline-head">EDIÇÃO DE PERFIL</h1>
                            </li>
                            <li id="profile">
                                <div class="timeline-badge primary"></div>
                                <div class="timeline-panel">
                                    <div class="form-group">
                                        @Html.EditorFor(model => model.DescriptionTitle, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.DescriptionTitle, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="hr-left"></div>
                                    <p>
                                        <div class="form-group">
                                            @Html.TextAreaFor(model => model.Description, 10, 20, htmlAttributes: new { @class = "form-control", data_provide="markdown", id="profile-description" })
                                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                        </div>
                                    </p>
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-addon"><i class="fa fa-twitter"></i></div>
                                            @Html.EditorFor(model => model.TwitterUrl, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.TwitterUrl, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-addon"><i class="fa fa-facebook-square"></i></div>
                                            @Html.EditorFor(model => model.FacebookUrl, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.FacebookUrl, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-addon"><i class="fa fa-google-plus"></i></div>
                                            @Html.EditorFor(model => model.GooglePlusUrl, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.GooglePlusUrl, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </li>
                            <!-- end:profile -->
                        </ul>
                    </div>
                    <!-- end:main content -->
                </div>
            </div>
        </div>
    </div>
    
}

@section Content {
    @Styles.Render("~/Content/user")
    @Styles.Render("~/Content/fa")
    @Styles.Render("~/Content/timeline")
    @Styles.Render("~/Content/markdown")
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/user")
    @Scripts.Render("~/bundles/scrolling-nav")
    @Scripts.Render("~/bundles/markdown")
}

PortalGuitarFlash.Web/Views/User/Index.cshtml
@model IEnumerable<PortalGuitarFlash.Web.ViewModels.UserViewModel>

@{
    ViewBag.Title = "Charters";
}

<h2>Charters</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CharterPoints)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegisterDate)
        </th>
    </tr>

    @foreach (var user in Model)
    {
        <tr class="clickable clickable-row" data-href="@Url.RouteUrl("Profile", new { id = user.ID }) ">
            <td>
                @Html.DisplayFor(modelItem => user.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => user.CharterPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => user.RegisterDate)
            </td>
        </tr>
    }

</table>

@Scripts.Render("~/bundles/user")

PortalGuitarFlash.Web/Views/User/Profile.cshtml
@model PortalGuitarFlash.Web.ViewModels.User.ProfileViewModel

<div class="container" id="main">
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
            <div id="sidebar">
                <div class="sosmed">
                    <div class="text-center">
                        @if (@Model.FacebookUrl != null)
                        {
                            <a href="@Model.FacebookUrl" target="_blank"><i class="fa fa-facebook fa-2x" data-toggle="tooltip" data-placement="top" title="Facebook"></i></a>
                        }
                        @if (@Model.TwitterUrl != null)
                        {
                            <a href="@Model.TwitterUrl" target="_blank"><i class="fa fa-twitter fa-2x" data-toggle="tooltip" data-placement="top" title="Twitter"></i></a>
                        }
                        @if (@Model.GooglePlusUrl != null)
                        {
                            <a href="@Model.GooglePlusUrl" target="_blank"><i class="fa fa-google-plus fa-2x" data-toggle="tooltip" data-placement="top" title="Google Plus"></i></a>
                        }
                    </div>
                </div>
                <div class="user">
                    <div class="text-center">
                        <img src="@Url.Action("UserProfileImage", "Image", new { userId = Model.ID })" class="img-circle img-profile">
                    </div>
                    <div class="user-head">
                        <h1 class="user-profile-name">@Model.Name.ToUpper()</h1>
                        <div class="hr-center"></div>
                    </div>
                </div>
                <div class="link-me">

                    <div class="text-center">
                        <div>@Model.Local</div>
                        <div>@Model.Age</div>
                        @if (@Model.Skype != null)
                        {
                            <div><i class="fa fa-skype"></i> @Model.Skype</div>
                        }
                    </div>
                    <div class="hr-center"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
            <div id="content">
                <!-- start:navbar -->
                <nav class="navbar navbar-default navbar-static-top" role="navigation">
                    <div class="navbar-header page-scroll">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="page-scroll">
                                <a href="#id-work">
                                    <i class="fa fa-angle-double-down"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <!-- end:navbar -->
                <!-- start:main content -->
                <div class="main-content">
                    <ul class="timeline">
                        <!-- start:profile -->
                        <li id="id-profile">
                            <div class="timeline-badge default"><i class="fa fa-user"></i></div>
                            <h1 class="timeline-head">PERFIL</h1>
                        </li>
                        <li id="profile">
                            <div class="timeline-badge primary"></div>
                            <div class="timeline-panel" >
                                <h1>@Model.DescriptionTitle</h1>
                                <div class="hr-left"></div>
                                <div class="markdown-editor">
                                    @Model.Description
                                </div>
                            </div>
                        </li>
                        <!-- end:profile -->
                        <!-- start:work -->
                        <li id="id-work">
                            <div class="timeline-badge default"><i class="fa fa-briefcase"></i></div>
                            <h1 class="timeline-head">GERAL</h1>
                        </li>
                        <li>
                            <div class="timeline-badge danger"></div>
                            <div class="timeline-panel">
                                <div class="timeline-body">
                                    <h1>Personal Info</h1>
                                </div>
                            </div>
                        </li>
                        <!-- end:work -->
                        <!-- start:resume -->
                        <li id="id-resume">
                            <div class="timeline-badge default"><i class="fa fa-file"></i></div>
                            <h1 class="timeline-head">MÚSICAS</h1>
                        </li>
                        <li id="resume">
                            <div class="timeline-badge warning"></div>
                            <div class="timeline-panel">
                                <h1>Músicas Custom</h1>
                                <div class="hr-left"></div>
                                <div class="songlist-item">
                                    <h3>Música A</h3>
                                    <small><i class="fa fa-calendar"></i>27/11/2015 03:34</small>
                                    <p>
                                        Duis aute irure dolor in reprehenderit in voluptate velit esse
                                        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                                    </p>
                                </div>
                                <hr>
                                <div class="songlist-item">
                                    <h3>Música B</h3>
                                    <small><i class="fa fa-calendar"></i>27/11/2015 03:34</small>
                                    <p>
                                        Duis aute irure dolor in reprehenderit in voluptate velit esse
                                        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                                    </p>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <!-- end:main content -->
            </div>
        </div>
    </div>
</div>

@section Content {
    @Styles.Render("~/Content/user")
    @Styles.Render("~/Content/fa")
    @Styles.Render("~/Content/timeline")
    @Styles.Render("~/Content/markdown")
}

@section Scripts {
    @Scripts.Render("~/bundles/user")
    @Scripts.Render("~/bundles/scrolling-nav")
    @Scripts.Render("~/bundles/markdown")
}